export { default as dcard } from './mycomponent/carta/carta';
export { default as navbar } from './mycomponent/navbar/navbar';
export { default as sidebar } from './mycomponent/sidebar/Suggestions';
export { default as card } from './mycomponent/carta/carta';
export { button } from './mycomponent/navbar/botones';
export { sideC } from './mycomponent/containersuggestion/suggestionsSection';
export { loginPge } from '../screens/login/login';
export { dashboard }  from '../screens/dashboard/dashboard'

export const direccionIndexPadre = "Hpla"